/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.Attribute;
import ca.uottawa.csmlab.symboleo.symboleo.ResourceAttribute;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.ResourceAttributeImpl#getResourceAt <em>Resource At</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResourceAttributeImpl extends ResourceImpl implements ResourceAttribute
{
  /**
   * The cached value of the '{@link #getResourceAt() <em>Resource At</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResourceAt()
   * @generated
   * @ordered
   */
  protected Attribute resourceAt;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.RESOURCE_ATTRIBUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getResourceAt()
  {
    return resourceAt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResourceAt(Attribute newResourceAt, NotificationChain msgs)
  {
    Attribute oldResourceAt = resourceAt;
    resourceAt = newResourceAt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT, oldResourceAt, newResourceAt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResourceAt(Attribute newResourceAt)
  {
    if (newResourceAt != resourceAt)
    {
      NotificationChain msgs = null;
      if (resourceAt != null)
        msgs = ((InternalEObject)resourceAt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT, null, msgs);
      if (newResourceAt != null)
        msgs = ((InternalEObject)newResourceAt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT, null, msgs);
      msgs = basicSetResourceAt(newResourceAt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT, newResourceAt, newResourceAt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT:
        return basicSetResourceAt(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT:
        return getResourceAt();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT:
        setResourceAt((Attribute)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT:
        setResourceAt((Attribute)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ATTRIBUTE__RESOURCE_AT:
        return resourceAt != null;
    }
    return super.eIsSet(featureID);
  }

} //ResourceAttributeImpl
