/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.Obligation;
import ca.uottawa.csmlab.symboleo.symboleo.ResourceObligation;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource Obligation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.ResourceObligationImpl#getResourceOp <em>Resource Op</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResourceObligationImpl extends ResourceImpl implements ResourceObligation
{
  /**
   * The cached value of the '{@link #getResourceOp() <em>Resource Op</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResourceOp()
   * @generated
   * @ordered
   */
  protected Obligation resourceOp;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceObligationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.RESOURCE_OBLIGATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Obligation getResourceOp()
  {
    if (resourceOp != null && resourceOp.eIsProxy())
    {
      InternalEObject oldResourceOp = (InternalEObject)resourceOp;
      resourceOp = (Obligation)eResolveProxy(oldResourceOp);
      if (resourceOp != oldResourceOp)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SymboleoPackage.RESOURCE_OBLIGATION__RESOURCE_OP, oldResourceOp, resourceOp));
      }
    }
    return resourceOp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Obligation basicGetResourceOp()
  {
    return resourceOp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResourceOp(Obligation newResourceOp)
  {
    Obligation oldResourceOp = resourceOp;
    resourceOp = newResourceOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_OBLIGATION__RESOURCE_OP, oldResourceOp, resourceOp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OBLIGATION__RESOURCE_OP:
        if (resolve) return getResourceOp();
        return basicGetResourceOp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OBLIGATION__RESOURCE_OP:
        setResourceOp((Obligation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OBLIGATION__RESOURCE_OP:
        setResourceOp((Obligation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OBLIGATION__RESOURCE_OP:
        return resourceOp != null;
    }
    return super.eIsSet(featureID);
  }

} //ResourceObligationImpl
