/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.Operation;
import ca.uottawa.csmlab.symboleo.symboleo.ResourceOperation;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource Operation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.ResourceOperationImpl#getResourceOpe <em>Resource Ope</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResourceOperationImpl extends ResourceImpl implements ResourceOperation
{
  /**
   * The cached value of the '{@link #getResourceOpe() <em>Resource Ope</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResourceOpe()
   * @generated
   * @ordered
   */
  protected Operation resourceOpe;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.RESOURCE_OPERATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation getResourceOpe()
  {
    return resourceOpe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResourceOpe(Operation newResourceOpe, NotificationChain msgs)
  {
    Operation oldResourceOpe = resourceOpe;
    resourceOpe = newResourceOpe;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE, oldResourceOpe, newResourceOpe);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResourceOpe(Operation newResourceOpe)
  {
    if (newResourceOpe != resourceOpe)
    {
      NotificationChain msgs = null;
      if (resourceOpe != null)
        msgs = ((InternalEObject)resourceOpe).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE, null, msgs);
      if (newResourceOpe != null)
        msgs = ((InternalEObject)newResourceOpe).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE, null, msgs);
      msgs = basicSetResourceOpe(newResourceOpe, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE, newResourceOpe, newResourceOpe));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE:
        return basicSetResourceOpe(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE:
        return getResourceOpe();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE:
        setResourceOpe((Operation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE:
        setResourceOpe((Operation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_OPERATION__RESOURCE_OPE:
        return resourceOpe != null;
    }
    return super.eIsSet(featureID);
  }

} //ResourceOperationImpl
