/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.ACPolicy;
import ca.uottawa.csmlab.symboleo.symboleo.ResourceACPolicy;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource AC Policy</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.ResourceACPolicyImpl#getResourceAc <em>Resource Ac</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResourceACPolicyImpl extends ResourceImpl implements ResourceACPolicy
{
  /**
   * The cached value of the '{@link #getResourceAc() <em>Resource Ac</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResourceAc()
   * @generated
   * @ordered
   */
  protected ACPolicy resourceAc;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceACPolicyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.RESOURCE_AC_POLICY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ACPolicy getResourceAc()
  {
    return resourceAc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResourceAc(ACPolicy newResourceAc, NotificationChain msgs)
  {
    ACPolicy oldResourceAc = resourceAc;
    resourceAc = newResourceAc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC, oldResourceAc, newResourceAc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResourceAc(ACPolicy newResourceAc)
  {
    if (newResourceAc != resourceAc)
    {
      NotificationChain msgs = null;
      if (resourceAc != null)
        msgs = ((InternalEObject)resourceAc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC, null, msgs);
      if (newResourceAc != null)
        msgs = ((InternalEObject)newResourceAc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC, null, msgs);
      msgs = basicSetResourceAc(newResourceAc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC, newResourceAc, newResourceAc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC:
        return basicSetResourceAc(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC:
        return getResourceAc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC:
        setResourceAc((ACPolicy)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC:
        setResourceAc((ACPolicy)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_AC_POLICY__RESOURCE_AC:
        return resourceAc != null;
    }
    return super.eIsSet(featureID);
  }

} //ResourceACPolicyImpl
