/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.OntologyType;
import ca.uottawa.csmlab.symboleo.symboleo.ResourceOntologyType;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource Ontology Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.ResourceOntologyTypeImpl#getResourceOn <em>Resource On</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResourceOntologyTypeImpl extends ResourceImpl implements ResourceOntologyType
{
  /**
   * The cached value of the '{@link #getResourceOn() <em>Resource On</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResourceOn()
   * @generated
   * @ordered
   */
  protected OntologyType resourceOn;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceOntologyTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.RESOURCE_ONTOLOGY_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OntologyType getResourceOn()
  {
    return resourceOn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResourceOn(OntologyType newResourceOn, NotificationChain msgs)
  {
    OntologyType oldResourceOn = resourceOn;
    resourceOn = newResourceOn;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON, oldResourceOn, newResourceOn);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResourceOn(OntologyType newResourceOn)
  {
    if (newResourceOn != resourceOn)
    {
      NotificationChain msgs = null;
      if (resourceOn != null)
        msgs = ((InternalEObject)resourceOn).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON, null, msgs);
      if (newResourceOn != null)
        msgs = ((InternalEObject)newResourceOn).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON, null, msgs);
      msgs = basicSetResourceOn(newResourceOn, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON, newResourceOn, newResourceOn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON:
        return basicSetResourceOn(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON:
        return getResourceOn();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON:
        setResourceOn((OntologyType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON:
        setResourceOn((OntologyType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_ONTOLOGY_TYPE__RESOURCE_ON:
        return resourceOn != null;
    }
    return super.eIsSet(featureID);
  }

} //ResourceOntologyTypeImpl
