/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.Ref;
import ca.uottawa.csmlab.symboleo.symboleo.ResourceDot;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Resource Dot</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.ResourceDotImpl#getResourceDot <em>Resource Dot</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResourceDotImpl extends ResourceImpl implements ResourceDot
{
  /**
   * The cached value of the '{@link #getResourceDot() <em>Resource Dot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResourceDot()
   * @generated
   * @ordered
   */
  protected Ref resourceDot;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResourceDotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.RESOURCE_DOT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ref getResourceDot()
  {
    return resourceDot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResourceDot(Ref newResourceDot, NotificationChain msgs)
  {
    Ref oldResourceDot = resourceDot;
    resourceDot = newResourceDot;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT, oldResourceDot, newResourceDot);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResourceDot(Ref newResourceDot)
  {
    if (newResourceDot != resourceDot)
    {
      NotificationChain msgs = null;
      if (resourceDot != null)
        msgs = ((InternalEObject)resourceDot).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT, null, msgs);
      if (newResourceDot != null)
        msgs = ((InternalEObject)newResourceDot).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT, null, msgs);
      msgs = basicSetResourceDot(newResourceDot, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT, newResourceDot, newResourceDot));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT:
        return basicSetResourceDot(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT:
        return getResourceDot();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT:
        setResourceDot((Ref)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT:
        setResourceDot((Ref)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RESOURCE_DOT__RESOURCE_DOT:
        return resourceDot != null;
    }
    return super.eIsSet(featureID);
  }

} //ResourceDotImpl
