/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.Permission;
import ca.uottawa.csmlab.symboleo.symboleo.Ref;
import ca.uottawa.csmlab.symboleo.symboleo.Resource;
import ca.uottawa.csmlab.symboleo.symboleo.Rule;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.RuleImpl#getName <em>Name</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.RuleImpl#getAction <em>Action</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.RuleImpl#getPermission <em>Permission</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.RuleImpl#getAccessedRole <em>Accessed Role</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.RuleImpl#getAccessedResource <em>Accessed Resource</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.RuleImpl#getController <em>Controller</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RuleImpl extends MinimalEObjectImpl.Container implements Rule
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAction() <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected static final String ACTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAction() <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected String action = ACTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getPermission() <em>Permission</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPermission()
   * @generated
   * @ordered
   */
  protected Permission permission;

  /**
   * The cached value of the '{@link #getAccessedRole() <em>Accessed Role</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccessedRole()
   * @generated
   * @ordered
   */
  protected Ref accessedRole;

  /**
   * The cached value of the '{@link #getAccessedResource() <em>Accessed Resource</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccessedResource()
   * @generated
   * @ordered
   */
  protected Resource accessedResource;

  /**
   * The cached value of the '{@link #getController() <em>Controller</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getController()
   * @generated
   * @ordered
   */
  protected Ref controller;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAction()
  {
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAction(String newAction)
  {
    String oldAction = action;
    action = newAction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__ACTION, oldAction, action));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Permission getPermission()
  {
    return permission;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPermission(Permission newPermission, NotificationChain msgs)
  {
    Permission oldPermission = permission;
    permission = newPermission;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__PERMISSION, oldPermission, newPermission);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPermission(Permission newPermission)
  {
    if (newPermission != permission)
    {
      NotificationChain msgs = null;
      if (permission != null)
        msgs = ((InternalEObject)permission).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__PERMISSION, null, msgs);
      if (newPermission != null)
        msgs = ((InternalEObject)newPermission).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__PERMISSION, null, msgs);
      msgs = basicSetPermission(newPermission, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__PERMISSION, newPermission, newPermission));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ref getAccessedRole()
  {
    return accessedRole;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAccessedRole(Ref newAccessedRole, NotificationChain msgs)
  {
    Ref oldAccessedRole = accessedRole;
    accessedRole = newAccessedRole;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__ACCESSED_ROLE, oldAccessedRole, newAccessedRole);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAccessedRole(Ref newAccessedRole)
  {
    if (newAccessedRole != accessedRole)
    {
      NotificationChain msgs = null;
      if (accessedRole != null)
        msgs = ((InternalEObject)accessedRole).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__ACCESSED_ROLE, null, msgs);
      if (newAccessedRole != null)
        msgs = ((InternalEObject)newAccessedRole).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__ACCESSED_ROLE, null, msgs);
      msgs = basicSetAccessedRole(newAccessedRole, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__ACCESSED_ROLE, newAccessedRole, newAccessedRole));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Resource getAccessedResource()
  {
    return accessedResource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAccessedResource(Resource newAccessedResource, NotificationChain msgs)
  {
    Resource oldAccessedResource = accessedResource;
    accessedResource = newAccessedResource;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__ACCESSED_RESOURCE, oldAccessedResource, newAccessedResource);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAccessedResource(Resource newAccessedResource)
  {
    if (newAccessedResource != accessedResource)
    {
      NotificationChain msgs = null;
      if (accessedResource != null)
        msgs = ((InternalEObject)accessedResource).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__ACCESSED_RESOURCE, null, msgs);
      if (newAccessedResource != null)
        msgs = ((InternalEObject)newAccessedResource).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__ACCESSED_RESOURCE, null, msgs);
      msgs = basicSetAccessedResource(newAccessedResource, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__ACCESSED_RESOURCE, newAccessedResource, newAccessedResource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ref getController()
  {
    return controller;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetController(Ref newController, NotificationChain msgs)
  {
    Ref oldController = controller;
    controller = newController;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__CONTROLLER, oldController, newController);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setController(Ref newController)
  {
    if (newController != controller)
    {
      NotificationChain msgs = null;
      if (controller != null)
        msgs = ((InternalEObject)controller).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__CONTROLLER, null, msgs);
      if (newController != null)
        msgs = ((InternalEObject)newController).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SymboleoPackage.RULE__CONTROLLER, null, msgs);
      msgs = basicSetController(newController, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.RULE__CONTROLLER, newController, newController));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SymboleoPackage.RULE__PERMISSION:
        return basicSetPermission(null, msgs);
      case SymboleoPackage.RULE__ACCESSED_ROLE:
        return basicSetAccessedRole(null, msgs);
      case SymboleoPackage.RULE__ACCESSED_RESOURCE:
        return basicSetAccessedResource(null, msgs);
      case SymboleoPackage.RULE__CONTROLLER:
        return basicSetController(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.RULE__NAME:
        return getName();
      case SymboleoPackage.RULE__ACTION:
        return getAction();
      case SymboleoPackage.RULE__PERMISSION:
        return getPermission();
      case SymboleoPackage.RULE__ACCESSED_ROLE:
        return getAccessedRole();
      case SymboleoPackage.RULE__ACCESSED_RESOURCE:
        return getAccessedResource();
      case SymboleoPackage.RULE__CONTROLLER:
        return getController();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.RULE__NAME:
        setName((String)newValue);
        return;
      case SymboleoPackage.RULE__ACTION:
        setAction((String)newValue);
        return;
      case SymboleoPackage.RULE__PERMISSION:
        setPermission((Permission)newValue);
        return;
      case SymboleoPackage.RULE__ACCESSED_ROLE:
        setAccessedRole((Ref)newValue);
        return;
      case SymboleoPackage.RULE__ACCESSED_RESOURCE:
        setAccessedResource((Resource)newValue);
        return;
      case SymboleoPackage.RULE__CONTROLLER:
        setController((Ref)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RULE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SymboleoPackage.RULE__ACTION:
        setAction(ACTION_EDEFAULT);
        return;
      case SymboleoPackage.RULE__PERMISSION:
        setPermission((Permission)null);
        return;
      case SymboleoPackage.RULE__ACCESSED_ROLE:
        setAccessedRole((Ref)null);
        return;
      case SymboleoPackage.RULE__ACCESSED_RESOURCE:
        setAccessedResource((Resource)null);
        return;
      case SymboleoPackage.RULE__CONTROLLER:
        setController((Ref)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.RULE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SymboleoPackage.RULE__ACTION:
        return ACTION_EDEFAULT == null ? action != null : !ACTION_EDEFAULT.equals(action);
      case SymboleoPackage.RULE__PERMISSION:
        return permission != null;
      case SymboleoPackage.RULE__ACCESSED_ROLE:
        return accessedRole != null;
      case SymboleoPackage.RULE__ACCESSED_RESOURCE:
        return accessedResource != null;
      case SymboleoPackage.RULE__CONTROLLER:
        return controller != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", action: ");
    result.append(action);
    result.append(')');
    return result.toString();
  }

} //RuleImpl
