/**
 * generated by Xtext 2.25.0
 */
package ca.uottawa.csmlab.symboleo.tests;

import ca.uottawa.csmlab.symboleo.symboleo.Model;
import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;

/* @ExtendWith(InjectionExtension.class) */@InjectWith(SymboleoInjectorProvider.class)
@SuppressWarnings("all")
public class SymboleoParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;

  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nassertNotNull cannot be resolved"
      + "\nassertTrue cannot be resolved");
  }
}
