/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Controller</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Controller#getControllerType <em>Controller Type</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getController()
 * @model
 * @generated
 */
public interface Controller extends EObject
{
  /**
   * Returns the value of the '<em><b>Controller Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controller Type</em>' containment reference.
   * @see #setControllerType(Ref)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getController_ControllerType()
   * @model containment="true"
   * @generated
   */
  Ref getControllerType();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Controller#getControllerType <em>Controller Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controller Type</em>' containment reference.
   * @see #getControllerType()
   * @generated
   */
  void setControllerType(Ref value);

} // Controller
