/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Eselfvent</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getEselfvent()
 * @model
 * @generated
 */
public interface Eselfvent extends Event
{
} // Eselfvent
