/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Dot Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.OperationDotExpression#getRef <em>Ref</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.OperationDotExpression#getTail <em>Tail</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getOperationDotExpression()
 * @model
 * @generated
 */
public interface OperationDotExpression extends Ref
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(Ref)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getOperationDotExpression_Ref()
   * @model containment="true"
   * @generated
   */
  Ref getRef();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.OperationDotExpression#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Ref value);

  /**
   * Returns the value of the '<em><b>Tail</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tail</em>' reference.
   * @see #setTail(Operation)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getOperationDotExpression_Tail()
   * @model
   * @generated
   */
  Operation getTail();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.OperationDotExpression#getTail <em>Tail</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tail</em>' reference.
   * @see #getTail()
   * @generated
   */
  void setTail(Operation value);

} // OperationDotExpression
