/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource Power</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ResourcePower#getResourcePo <em>Resource Po</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourcePower()
 * @model
 * @generated
 */
public interface ResourcePower extends Resource
{
  /**
   * Returns the value of the '<em><b>Resource Po</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Po</em>' reference.
   * @see #setResourcePo(Power)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourcePower_ResourcePo()
   * @model
   * @generated
   */
  Power getResourcePo();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ResourcePower#getResourcePo <em>Resource Po</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Po</em>' reference.
   * @see #getResourcePo()
   * @generated
   */
  void setResourcePo(Power value);

} // ResourcePower
