/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceAttribute#getResourceAt <em>Resource At</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceAttribute()
 * @model
 * @generated
 */
public interface ResourceAttribute extends Resource
{
  /**
   * Returns the value of the '<em><b>Resource At</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource At</em>' containment reference.
   * @see #setResourceAt(Attribute)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceAttribute_ResourceAt()
   * @model containment="true"
   * @generated
   */
  Attribute getResourceAt();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceAttribute#getResourceAt <em>Resource At</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource At</em>' containment reference.
   * @see #getResourceAt()
   * @generated
   */
  void setResourceAt(Attribute value);

} // ResourceAttribute
