/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceOperation#getResourceOpe <em>Resource Ope</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceOperation()
 * @model
 * @generated
 */
public interface ResourceOperation extends Resource
{
  /**
   * Returns the value of the '<em><b>Resource Ope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Ope</em>' containment reference.
   * @see #setResourceOpe(Operation)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceOperation_ResourceOpe()
   * @model containment="true"
   * @generated
   */
  Operation getResourceOpe();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceOperation#getResourceOpe <em>Resource Ope</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Ope</em>' containment reference.
   * @see #getResourceOpe()
   * @generated
   */
  void setResourceOpe(Operation value);

} // ResourceOperation
