/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource Obligation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceObligation#getResourceOp <em>Resource Op</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceObligation()
 * @model
 * @generated
 */
public interface ResourceObligation extends Resource
{
  /**
   * Returns the value of the '<em><b>Resource Op</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Op</em>' reference.
   * @see #setResourceOp(Obligation)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceObligation_ResourceOp()
   * @model
   * @generated
   */
  Obligation getResourceOp();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceObligation#getResourceOp <em>Resource Op</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Op</em>' reference.
   * @see #getResourceOp()
   * @generated
   */
  void setResourceOp(Obligation value);

} // ResourceObligation
