/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResource()
 * @model
 * @generated
 */
public interface Resource extends EObject
{
} // Resource
