/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource Ontology Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceOntologyType#getResourceOn <em>Resource On</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceOntologyType()
 * @model
 * @generated
 */
public interface ResourceOntologyType extends Resource
{
  /**
   * Returns the value of the '<em><b>Resource On</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource On</em>' containment reference.
   * @see #setResourceOn(OntologyType)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceOntologyType_ResourceOn()
   * @model containment="true"
   * @generated
   */
  OntologyType getResourceOn();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceOntologyType#getResourceOn <em>Resource On</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource On</em>' containment reference.
   * @see #getResourceOn()
   * @generated
   */
  void setResourceOn(OntologyType value);

} // ResourceOntologyType
