/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource Dot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceDot#getResourceDot <em>Resource Dot</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceDot()
 * @model
 * @generated
 */
public interface ResourceDot extends Resource
{
  /**
   * Returns the value of the '<em><b>Resource Dot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Dot</em>' containment reference.
   * @see #setResourceDot(Ref)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceDot_ResourceDot()
   * @model containment="true"
   * @generated
   */
  Ref getResourceDot();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceDot#getResourceDot <em>Resource Dot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Dot</em>' containment reference.
   * @see #getResourceDot()
   * @generated
   */
  void setResourceDot(Ref value);

} // ResourceDot
