/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource AC Policy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceACPolicy#getResourceAc <em>Resource Ac</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceACPolicy()
 * @model
 * @generated
 */
public interface ResourceACPolicy extends Resource
{
  /**
   * Returns the value of the '<em><b>Resource Ac</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Ac</em>' containment reference.
   * @see #setResourceAc(ACPolicy)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getResourceACPolicy_ResourceAc()
   * @model containment="true"
   * @generated
   */
  ACPolicy getResourceAc();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ResourceACPolicy#getResourceAc <em>Resource Ac</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Ac</em>' containment reference.
   * @see #getResourceAc()
   * @generated
   */
  void setResourceAc(ACPolicy value);

} // ResourceACPolicy
