/**
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getName <em>Name</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getAction <em>Action</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getPermission <em>Permission</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getAccessedRole <em>Accessed Role</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getAccessedResource <em>Accessed Resource</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getController <em>Controller</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRule_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

  /**
   * Returns the value of the '<em><b>Permission</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Permission</em>' containment reference.
   * @see #setPermission(Permission)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRule_Permission()
   * @model containment="true"
   * @generated
   */
  Permission getPermission();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getPermission <em>Permission</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Permission</em>' containment reference.
   * @see #getPermission()
   * @generated
   */
  void setPermission(Permission value);

  /**
   * Returns the value of the '<em><b>Accessed Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Accessed Role</em>' containment reference.
   * @see #setAccessedRole(Ref)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRule_AccessedRole()
   * @model containment="true"
   * @generated
   */
  Ref getAccessedRole();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getAccessedRole <em>Accessed Role</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Accessed Role</em>' containment reference.
   * @see #getAccessedRole()
   * @generated
   */
  void setAccessedRole(Ref value);

  /**
   * Returns the value of the '<em><b>Accessed Resource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Accessed Resource</em>' containment reference.
   * @see #setAccessedResource(Resource)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRule_AccessedResource()
   * @model containment="true"
   * @generated
   */
  Resource getAccessedResource();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getAccessedResource <em>Accessed Resource</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Accessed Resource</em>' containment reference.
   * @see #getAccessedResource()
   * @generated
   */
  void setAccessedResource(Resource value);

  /**
   * Returns the value of the '<em><b>Controller</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controller</em>' containment reference.
   * @see #setController(Ref)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRule_Controller()
   * @model containment="true"
   * @generated
   */
  Ref getController();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Rule#getController <em>Controller</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controller</em>' containment reference.
   * @see #getController()
   * @generated
   */
  void setController(Ref value);

} // Rule
