/*
 * generated by Xtext 2.25.0
 */
package ca.uottawa.csmlab.symboleo.validation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

import ca.uottawa.csmlab.symboleo.Helpers;
import ca.uottawa.csmlab.symboleo.ResolveExpressionResult;
import ca.uottawa.csmlab.symboleo.symboleo.ACPolicy;
import ca.uottawa.csmlab.symboleo.symboleo.AssignExpression;
import ca.uottawa.csmlab.symboleo.symboleo.AtomicExpressionParameter;
import ca.uottawa.csmlab.symboleo.symboleo.Expression;
//import ca.uottawa.csmlab.symboleo.symboleo.AssignVariable;
import ca.uottawa.csmlab.symboleo.symboleo.Assignment;
import ca.uottawa.csmlab.symboleo.symboleo.Attribute;
import ca.uottawa.csmlab.symboleo.symboleo.AttributeModifier;
import ca.uottawa.csmlab.symboleo.symboleo.BaseType;
import ca.uottawa.csmlab.symboleo.symboleo.Controller;
import ca.uottawa.csmlab.symboleo.symboleo.DomainType;
import ca.uottawa.csmlab.symboleo.symboleo.Event;
import ca.uottawa.csmlab.symboleo.symboleo.FunctionCall;
import ca.uottawa.csmlab.symboleo.symboleo.Model;
import ca.uottawa.csmlab.symboleo.symboleo.Obligation;
import ca.uottawa.csmlab.symboleo.symboleo.OneArgMathFunction;
import ca.uottawa.csmlab.symboleo.symboleo.OneArgStringFunction;
import ca.uottawa.csmlab.symboleo.symboleo.OntologyType;
import ca.uottawa.csmlab.symboleo.symboleo.Parameter;
import ca.uottawa.csmlab.symboleo.symboleo.Proposition;
import ca.uottawa.csmlab.symboleo.symboleo.ParameterType;
import ca.uottawa.csmlab.symboleo.symboleo.Power;
import ca.uottawa.csmlab.symboleo.symboleo.Ref;
import ca.uottawa.csmlab.symboleo.symboleo.RegularType;
import ca.uottawa.csmlab.symboleo.symboleo.Resource;
import ca.uottawa.csmlab.symboleo.symboleo.ResourceDot;
import ca.uottawa.csmlab.symboleo.symboleo.Rule;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;
import ca.uottawa.csmlab.symboleo.symboleo.ThreeArgDateFunction;
import ca.uottawa.csmlab.symboleo.symboleo.ThreeArgStringFunction;
import ca.uottawa.csmlab.symboleo.symboleo.TimevalueVariable;
import ca.uottawa.csmlab.symboleo.symboleo.TwoArgMathFunction;
import ca.uottawa.csmlab.symboleo.symboleo.TwoArgStringFunction;
import ca.uottawa.csmlab.symboleo.symboleo.Variable;
import ca.uottawa.csmlab.symboleo.symboleo.VariableDotExpression;
import ca.uottawa.csmlab.symboleo.symboleo.VariableEvent;
import ca.uottawa.csmlab.symboleo.symboleo.VariableRef;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SymboleoValidator extends AbstractSymboleoValidator {

  List<Variable> variables;
  List<Parameter> parameters;

  private static String withUpperInitial(String name) {
    return Character.toUpperCase(name.charAt(0)) + name.substring(1);
  }

  private static String withLowerInitial(String name) {
    return Character.toLowerCase(name.charAt(0)) + name.substring(1);
  }

  @Check(CheckType.FAST)
  public void checkDomainTypesStartWithCapital(DomainType type) {
    if (!Character.isUpperCase(type.getName().charAt(0))) {
      error("Domain type name '" + type.getName() + "' must start with a "
          + "capital letter (type names become class names in the generated "
          + "code). Rename it to '" + withUpperInitial(type.getName())
          + "' here and at every reference.", type,
          SymboleoPackage.Literals.DOMAIN_TYPE__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkParametersStartWithLowerCase(Parameter p) {
    if (!Character.isLowerCase(p.getName().charAt(0))) {
      error("Contract parameter name '" + p.getName() + "' must start with a "
          + "lowercase letter (capitalized names are reserved for domain "
          + "types). Rename it to '" + withLowerInitial(p.getName())
          + "' here and at every reference.", p,
          SymboleoPackage.Literals.PARAMETER__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkVariablesStartWithLowerCase(Variable v) {
    if (!Character.isLowerCase(v.getName().charAt(0))) {
      error("Variable name '" + v.getName() + "' must start with a lowercase "
          + "letter (capitalized names are reserved for domain types). Rename "
          + "it to '" + withLowerInitial(v.getName())
          + "' here and at every reference.", v,
          SymboleoPackage.Literals.VARIABLE__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkObligationsStartWithLowerCase(Obligation o) {
    if (!Character.isLowerCase(o.getName().charAt(0))) {
      error("Obligation name '" + o.getName() + "' must start with a "
          + "lowercase letter. Rename it to '" + withLowerInitial(o.getName())
          + "' here and at every reference (e.g. obligations."
          + withLowerInitial(o.getName()) + ").", o,
          SymboleoPackage.Literals.OBLIGATION__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkPowersStartWithLowerCase(Power o) {
    if (!Character.isLowerCase(o.getName().charAt(0))) {
      error("Power name '" + o.getName() + "' must start with a lowercase "
          + "letter. Rename it to '" + withLowerInitial(o.getName())
          + "' here and at every reference.", o,
          SymboleoPackage.Literals.POWER__NAME);
    }
  }

  /*
   * Identifiers should be unique
   */
  @Check(CheckType.FAST)
  public void checkIdentifiersAreUnique(Model model) {
    this.variables = model.getVariables();
    this.parameters = model.getParameters();

    Set<String> identifiers = new HashSet<>();

    for (Parameter x : model.getParameters()) {
      if (identifiers.contains(x.getName())) {
        error("Duplicate identifier '" + x.getName() + "': contract "
            + "parameters and declared instances share one namespace, and "
            + "this name is already taken. Rename or remove one of the two "
            + "declarations (update every reference to the renamed one).", x,
            SymboleoPackage.Literals.PARAMETER__NAME);
      }
      identifiers.add(x.getName());
    }

    for (Variable x : model.getVariables()) {
      if (identifiers.contains(x.getName())) {
        error("Duplicate identifier '" + x.getName() + "': contract "
            + "parameters and declared instances share one namespace, and "
            + "this name is already taken. Rename or remove one of the two "
            + "declarations (update every reference to the renamed one).", x,
            SymboleoPackage.Literals.VARIABLE__NAME);
      }
      identifiers.add(x.getName());
    }
  }

  /*
   * Identifiers should be unique
   */
  @Check(CheckType.FAST)
  public void checkIdentifiersAreUnique2(Model model) {

    Set<String> identifiers = new HashSet<>();

    for (Obligation x : model.getObligations()) {
      if (identifiers.contains(x.getName())) {
        error(duplicateNormMessage(x.getName()), x, SymboleoPackage.Literals.OBLIGATION__NAME);
      }
      identifiers.add(x.getName());
    }

    for (Obligation x : model.getSurvivingObligations()) {
      if (identifiers.contains(x.getName())) {
        error(duplicateNormMessage(x.getName()), x, SymboleoPackage.Literals.OBLIGATION__NAME);
      }
      identifiers.add(x.getName());
    }

    for (Power x : model.getPowers()) {
      if (identifiers.contains(x.getName())) {
        error(duplicateNormMessage(x.getName()), x, SymboleoPackage.Literals.POWER__NAME);
      }
      identifiers.add(x.getName());
    }
  }

  private static String duplicateNormMessage(String name) {
    return "Duplicate norm identifier '" + name + "': obligations, surviving "
        + "obligations, and powers share one namespace (powers reference them "
        + "as obligations.<name>), and this name is already taken. Rename one "
        + "of the two norms and update every reference to it.";
  }

  /*
   * Check that model properties have unique names
   */
  @Check(CheckType.FAST)
  public void checkModelAttributesAreUnique(DomainType type) {
    if (type instanceof RegularType) {
      // set of property names
      Set<String> identifiers = new HashSet<>();
      // iterate over all properties of the model
      for (Attribute atr : Helpers.getAttributesOfRegularType((RegularType) type)) {
        if (identifiers.contains(atr.getName())) {
          error("Duplicate attribute name '" + atr.getName() + "' in domain "
              + "type '" + type.getName() + "'. Attributes inherited through "
              + "isA count too, so the clash may be with a supertype's "
              + "attribute. Rename or remove one of the two declarations.", atr,
              SymboleoPackage.Literals.ATTRIBUTE__NAME);
        }
        identifiers.add(atr.getName());
      }
    }
  }

  /*
   * Check that Env is only used for Event types
   */
  //AC-we added DataTransfer here as a special kind of event that use Env
  @Check(CheckType.FAST)
  public void checkEnvUsageIsValid(DomainType type) {
    if (type instanceof RegularType) {
      // check that base type is Event
      boolean isEvent = Helpers.getBaseType(type).getOntologyType().getName().equalsIgnoreCase("Event") || Helpers.getBaseType(type).getOntologyType().getName().equalsIgnoreCase("DataTransfer") ;
      for (Attribute atr : ((RegularType) type).getAttributes()) {
        if (atr.getAttributeModifier() != null) {
          AttributeModifier mod = atr.getAttributeModifier();
          // if is not a type of Event and Env is used then show error
          if (mod.getName().equalsIgnoreCase("Env") && !isEvent) {
            error("The 'Env' modifier on attribute '" + atr.getName() + "' of '"
                + type.getName() + "' is only allowed inside Event (or "
                + "DataTransfer) types -- Env marks values the runtime supplies "
                + "when the event happens. Remove the Env modifier, or make '"
                + type.getName() + "' an Event subtype (isA ... isA Event).", atr,
                SymboleoPackage.Literals.ATTRIBUTE__NAME);
          }
        }
      }
    }
  }

  /*
   * check that variable initiations are valid
   */
  @Check(CheckType.FAST)
  public void checkInitializationsAreValid(Variable var) {
    RegularType type = var.getType();

    // get list of assignments
    List<Assignment> assignments = var.getAttributes();
    for (Attribute atr : Helpers.getAttributesOfRegularType((RegularType) type)) {
      // find that the attribute is assigned
      Optional<Assignment> res = assignments.stream()
          .filter(a -> ((AssignExpression) a).getName().equals(atr.getName())).findFirst();
      boolean isInitiated = res.isPresent();
      if (atr.getAttributeModifier() != null) {
        AttributeModifier mod = atr.getAttributeModifier();
        // Env values shall not be set
        if (mod.getName().equalsIgnoreCase("Env") && isInitiated) {
          error("Env attribute '" + ((AssignExpression) res.get()).getName()
              + "' of type '" + type.getName() + "' must not be assigned in a "
              + "declaration -- Env values are supplied by the runtime "
              + "environment when the event happens. Remove the ':=' "
              + "assignment for it from the declaration of '" + var.getName()
              + "'.", res.get(), SymboleoPackage.Literals.ASSIGN_EXPRESSION__NAME);
        }
      } else if (!isInitiated && !atr.getName().equalsIgnoreCase("_timestamp")) {
        // all other attributes should be initiated
        error("Attribute '" + atr.getName() + "' of type '" + type.getName()
            + "' is not assigned in the declaration of '" + var.getName()
            + "'. Every non-Env attribute must be assigned: add '"
            + atr.getName() + " := <value>' to the 'with' clause (only "
            + "Env attributes are left unassigned, for the runtime to fill).",
            var, SymboleoPackage.Literals.VARIABLE__ATTRIBUTES);
      }
    }
  }

  /*
   * check that assignments are valid
   */
  @Check(CheckType.FAST)
  public void checkAssignmentsName(Variable var) {
    RegularType type = var.getType();

    // get list of type attributes
    List<Attribute> attributes = Helpers.getAttributesOfRegularType((RegularType) type);
    for (Assignment assignment : var.getAttributes()) {
      // find that the assignment name is in the model
      AssignExpression asgExp = (AssignExpression) assignment;
      Optional<Attribute> res = attributes.stream().filter(atr -> atr.getName().equals(asgExp.getName())).findFirst();
      if (res.isEmpty()) {
        error("The declaration of '" + var.getName() + "' assigns '"
            + asgExp.getName() + "', but its type '" + type.getName()
            + "' declares no attribute with that name (inherited attributes "
            + "were checked too). Fix the attribute name, add the attribute "
            + "to the type, or remove the assignment.", assignment,
            SymboleoPackage.Literals.ASSIGN_EXPRESSION__NAME);
      }
    }
  }

  private static String roleMessage(String position, String normKind, String name) {
    return "The " + position + " of " + normKind + " '" + name + "' must be a "
        + "role instance: a variable or contract parameter whose type is "
        + "declared 'isA Role'. Reference a Role-typed variable/parameter "
        + "here, or change the referenced element's type so it isA Role.";
  }

  /*
   * check type of creditor and debtor
   */
  @Check(CheckType.FAST)
  public void checkCreditorAndDebtor(Model model) {
    // loop over powers
    for (Power power : model.getPowers()) {
      // check debtor type
      EObject debtorType = Helpers.getDotExpressionType(power.getDebtor(), model.getVariables(), model.getParameters());
      // get the parameter type if it is a parameter
      if (debtorType instanceof ParameterType && ((ParameterType) debtorType).getDomainType() != null) {
        debtorType = ((ParameterType) debtorType).getDomainType();
      }
      if (debtorType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) debtorType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error(roleMessage("debtor", "power", power.getName()), power,
              SymboleoPackage.Literals.POWER__DEBTOR);
        }
      } else {
        error(roleMessage("debtor", "power", power.getName()), power,
            SymboleoPackage.Literals.POWER__DEBTOR);
      }

      // check creditor type
      EObject creditorType = Helpers.getDotExpressionType(power.getCreditor(), model.getVariables(),
          model.getParameters());
      // get the parameter type if it is a parameter
      if (creditorType instanceof ParameterType && ((ParameterType) creditorType).getDomainType() != null) {
        creditorType = ((ParameterType) creditorType).getDomainType();
      }
      if (creditorType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) creditorType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error(roleMessage("creditor", "power", power.getName()), power,
              SymboleoPackage.Literals.POWER__CREDITOR);
        }
      } else {
        error(roleMessage("creditor", "power", power.getName()), power,
            SymboleoPackage.Literals.POWER__CREDITOR);
      }
    }

    // loop over obligations
    for (Obligation obligation : model.getObligations()) {
      // check debtor type
      EObject debtorType = Helpers.getDotExpressionType(obligation.getDebtor(), model.getVariables(),
          model.getParameters());
      // get the parameter type if it is a parameter
      if (debtorType instanceof ParameterType && ((ParameterType) debtorType).getDomainType() != null) {
        debtorType = ((ParameterType) debtorType).getDomainType();
      }
      if (debtorType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) debtorType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error(roleMessage("debtor", "obligation", obligation.getName()), obligation,
              SymboleoPackage.Literals.OBLIGATION__DEBTOR);
        }
      } else {
        error(roleMessage("debtor", "obligation", obligation.getName()), obligation,
            SymboleoPackage.Literals.OBLIGATION__DEBTOR);
      }
      // check creditor type
      EObject creditorType = Helpers.getDotExpressionType(obligation.getCreditor(), model.getVariables(),
          model.getParameters());
      // get the parameter type if it is a parameter
      if (creditorType instanceof ParameterType && ((ParameterType) creditorType).getDomainType() != null) {
        creditorType = ((ParameterType) creditorType).getDomainType();
      }
      if (creditorType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) creditorType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error(roleMessage("creditor", "obligation", obligation.getName()), obligation,
              SymboleoPackage.Literals.OBLIGATION__CREDITOR);
        }
      } else {
        error(roleMessage("creditor", "obligation", obligation.getName()), obligation,
            SymboleoPackage.Literals.OBLIGATION__CREDITOR);
      }
    }

    // loop over surviving obligations
    for (Obligation obligation : model.getSurvivingObligations()) {
      // check debtor type
      EObject debtorType = Helpers.getDotExpressionType(obligation.getDebtor(), model.getVariables(),
          model.getParameters());
      // get the parameter type if it is a parameter
      if (debtorType instanceof ParameterType && ((ParameterType) debtorType).getDomainType() != null) {
        debtorType = ((ParameterType) debtorType).getDomainType();
      }
      if (debtorType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) debtorType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error(roleMessage("debtor", "obligation", obligation.getName()), obligation,
              SymboleoPackage.Literals.OBLIGATION__DEBTOR);
        }
      } else {
        error(roleMessage("debtor", "obligation", obligation.getName()), obligation,
            SymboleoPackage.Literals.OBLIGATION__DEBTOR);
      }
      // check creditor type
      EObject creditorType = Helpers.getDotExpressionType(obligation.getCreditor(), model.getVariables(),
          model.getParameters());
      // get the parameter type if it is a parameter
      if (creditorType instanceof ParameterType && ((ParameterType) creditorType).getDomainType() != null) {
        creditorType = ((ParameterType) creditorType).getDomainType();
      }
      if (creditorType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) creditorType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error(roleMessage("creditor", "obligation", obligation.getName()), obligation,
              SymboleoPackage.Literals.OBLIGATION__CREDITOR);
        }
      } else {
        error(roleMessage("creditor", "obligation", obligation.getName()), obligation,
            SymboleoPackage.Literals.OBLIGATION__CREDITOR);
      }
    }

  }

  /*
   * check assignment types
   */
  @Check(CheckType.FAST)
  public void checkExpressionVariables(VariableRef var) {
    // each VariableRef in VariableDotExpression should be declared first
    EObject typeObject = Helpers.getDotExpressionType(var, this.variables, this.parameters);
    if (typeObject == null) {
      error("'" + var.getVariable() + "' is not declared: it is neither a "
          + "declared instance (Declarations section) nor a contract "
          + "parameter. Declare it (e.g. '" + var.getVariable()
          + ": SomeType with attr := ...;'), add it to the contract's "
          + "parameter list, or fix the reference -- identifiers are "
          + "case-sensitive.", var,
          SymboleoPackage.Literals.VARIABLE_REF__VARIABLE);
    }
  }

  /*
   * check assignment types
   */
  @Check(CheckType.NORMAL)
  public void checkExpressionTypes(Model model) {
    // run the check for every variable
    for (Variable var : model.getVariables()) {
      RegularType modelType = var.getType();
      // get all attributes of the type
      List<Attribute> attributes = Helpers.getAttributesOfRegularType((RegularType) modelType);
      for (Assignment asg : var.getAttributes()) {
        // find the type in the model
        Optional<Attribute> res = attributes.stream()
            .filter(atr -> atr.getName().equals(((AssignExpression) asg).getName())).findFirst();
        if (!res.isEmpty()) {
          Attribute atr = res.get();
          String atrType = null;

          // get attribute type
          if (atr.getDomainType() != null) {
            atrType = Helpers.handleDomainType(atr.getDomainType()).type;
          } else if (atr.getBaseType() != null) {
            atrType = atr.getBaseType().getName();
          }

          if (asg instanceof AssignExpression) {
            AssignExpression asgExp = (AssignExpression) asg;
            // resolve expression type
            ResolveExpressionResult typeRes = Helpers.resolveExpressionType(asgExp.getValue(), model.getVariables(),
                model.getParameters());
            if (typeRes.error != null) {
              // if there is an error in resolving the type, show the error
              error(typeRes.message, typeRes.error, typeRes.ref);
            }
            if (!typeRes.type.equals(atrType)) {
              // if type does not match
              error("Type mismatch in the declaration of '" + var.getName()
                  + "': attribute '" + asgExp.getName() + "' is declared as '"
                  + atrType + "' but the assigned expression has type '"
                  + typeRes.type + "'. Change the assigned value to a '"
                  + atrType + "', or change the attribute's declared type.",
                  asg, SymboleoPackage.Literals.ASSIGN_EXPRESSION__NAME);
            }
          }
//          else if (asg instanceof AssignVariable) {
//            // resolve VariableDotExpression type
//            ResolveExpressionResult typeRes = Helpers.getVariableExpressionType(
//                ((AssignVariable) asg).getValue(), model.getVariables(),
//                model.getParameters());
//            if (!typeRes.type.equals(atrType)) {
//              error(
//                  "Type of '" + asg.getName() + "' in " + var.getName()
//                      + " does not match",
//                  asg, SymboleoPackage.Literals.ASSIGNMENT__NAME);
//            }
//          }
        }
      }
    }
  }

  // L4: is this expression a bare Event variable (used as its occurrence
  // date point)? True iff it is a plain variable reference -- no attribute
  // tail -- to a variable whose type is (transitively) isA Event.
  private boolean isEventPoint(Expression e) {
    if (!(e instanceof AtomicExpressionParameter)) {
      return false;
    }
    Object ref = ((AtomicExpressionParameter) e).getValue();
    if (!(ref instanceof VariableRef)) {
      return false; // a VariableDotExpression is event.attr, not the event itself
    }
    String name = ((VariableRef) ref).getVariable();
    List<Variable> vars = this.variables != null ? this.variables : java.util.Collections.emptyList();
    for (Variable v : vars) {
      if (name.equals(v.getName()) && v.getType() != null) {
        RegularType base = Helpers.getBaseType(v.getType());
        return base != null && base.getOntologyType() != null
            && base.getOntologyType().getName().equalsIgnoreCase("Event");
      }
    }
    return false;
  }

  private static String argTypeMessage(String ordinal, String func,
      String expected, String found) {
    return "The " + ordinal + " argument of '" + func + "' must be a "
        + expected + ", but the given expression has type '" + found
        + "'. Pass a " + expected + "-typed expression (a literal, a "
        + "contract parameter, or an attribute of that type).";
  }

  /*
   * check type of internal functions
   */
  @Check(CheckType.FAST)
  public void checkMathFunctionArgsType(OneArgMathFunction function) {
    // resolve type of argument
    ResolveExpressionResult typeRes = Helpers.resolveExpressionType(function.getArg1(), this.variables,
        this.parameters);
    // show error if not a number
    if (typeRes.error != null) {
      error(typeRes.message, typeRes.error, typeRes.ref);
    }
    if (!typeRes.type.equals("Number")) {
      error(argTypeMessage("first", function.getName(), "Number", typeRes.type), function,
          SymboleoPackage.Literals.FUNCTION_CALL__ARG1);
    }
    warnUnsupportedFunction(function);
  }

  /*
   * check type of internal functions
   */
  @Check(CheckType.FAST)
  public void checkMathFunctionArgsType2(TwoArgMathFunction function) {
    // resolve type of argument
    ResolveExpressionResult typeRes = Helpers.resolveExpressionType(function.getArg1(), this.variables,
        this.parameters);
    ResolveExpressionResult typeRes2 = Helpers.resolveExpressionType(function.getArg2(), this.variables,
        this.parameters);
    // show error if not a number
    if (typeRes.error != null) {
      error(typeRes.message, typeRes.error, typeRes.ref);
    }
    if (typeRes2.error != null) {
      error(typeRes2.message, typeRes2.error, typeRes2.ref);
    }
    if (!typeRes.type.equals("Number")) {
      error(argTypeMessage("first", function.getName(), "Number", typeRes.type), function,
          SymboleoPackage.Literals.FUNCTION_CALL__ARG1);
    }
    if (!typeRes2.type.equals("Number")) {
      error(argTypeMessage("second", function.getName(), "Number", typeRes2.type), function,
          SymboleoPackage.Literals.TWO_ARG_MATH_FUNCTION__ARG2);
    }
    //Only warn if the function is Math.pow 
    if(function.getName().equals("Math.pow")){
    	warnUnsupportedFunction(function);
    }
  }

  /*
   * check type of internal functions
   */
  @Check(CheckType.FAST)
  public void checkStringFunctionArgsType(OneArgStringFunction function) {
    // resolve type of argument
    ResolveExpressionResult typeRes = Helpers.resolveExpressionType(function.getArg1(), this.variables,
        this.parameters);
    // show error if not a string
    if (typeRes.error != null) {
      error(typeRes.message, typeRes.error, typeRes.ref);
    }
    if (!typeRes.type.equals("String")) {
      error(argTypeMessage("first", function.getName(), "String", typeRes.type), function,
          SymboleoPackage.Literals.FUNCTION_CALL__ARG1);
    }
    warnUnsupportedFunction(function);
  }

  /*
   * check type of internal functions
   */
  @Check(CheckType.FAST)
  public void checkStringFunctionArgsType2(TwoArgStringFunction function) {
    // resolve type of argument
    ResolveExpressionResult typeRes = Helpers.resolveExpressionType(function.getArg1(), this.variables,
        this.parameters);
    ResolveExpressionResult typeRes2 = Helpers.resolveExpressionType(function.getArg2(), this.variables,
        this.parameters);
    // show error if not a string
    if (typeRes.error != null) {
      error(typeRes.message, typeRes.error, typeRes.ref);
    }
    if (typeRes2.error != null) {
      error(typeRes2.message, typeRes2.error, typeRes2.ref);
    }
    if (!typeRes.type.equals("String")) {
      error(argTypeMessage("first", function.getName(), "String", typeRes.type), function,
          SymboleoPackage.Literals.FUNCTION_CALL__ARG1);
    }
    if (!typeRes2.type.equals("String")) {
      error(argTypeMessage("second", function.getName(), "String", typeRes2.type), function,
          SymboleoPackage.Literals.TWO_ARG_STRING_FUNCTION__ARG2);
    }
    warnUnsupportedFunction(function);
  }

  /*
   * check type of internal functions
   */
  @Check(CheckType.FAST)
  public void checkStringFunctionArgsType3(ThreeArgStringFunction function) {
    // resolve type of argument
    ResolveExpressionResult typeRes = Helpers.resolveExpressionType(function.getArg1(), this.variables,
        this.parameters);
    ResolveExpressionResult typeRes2 = Helpers.resolveExpressionType(function.getArg2(), this.variables,
        this.parameters);
    ResolveExpressionResult typeRes3 = Helpers.resolveExpressionType(function.getArg3(), this.variables,
        this.parameters);

    if (typeRes2.error != null) {
      error(typeRes2.message, typeRes2.error, typeRes2.ref);
    }
    if (typeRes3.error != null) {
      error(typeRes3.message, typeRes3.error, typeRes3.ref);
    }
    // show error if not a string
    if (typeRes.error != null) {
      error(typeRes.message, typeRes.error, typeRes.ref);
    }
    if (!typeRes.type.equals("String")) {
      error(argTypeMessage("first", function.getName(), "String", typeRes.type), function,
          SymboleoPackage.Literals.FUNCTION_CALL__ARG1);
    }

    if (function.getName().equals("String.replace") || function.getName().equals("String.replaceAll")) {
      if (!typeRes2.type.equals("String")) {
        error(argTypeMessage("second", function.getName(), "String", typeRes2.type), function,
            SymboleoPackage.Literals.THREE_ARG_STRING_FUNCTION__ARG2);
      }
      if (!typeRes3.type.equals("String")) {
        error(argTypeMessage("third", function.getName(), "String", typeRes3.type), function,
            SymboleoPackage.Literals.THREE_ARG_STRING_FUNCTION__ARG3);
      }
    } else if (function.getName().equals("String.substring")) {
      // second and third args of substring are number
      if (!typeRes2.type.equals("Number")) {
        error(argTypeMessage("second", function.getName(), "Number", typeRes2.type), function,
            SymboleoPackage.Literals.THREE_ARG_STRING_FUNCTION__ARG2);
      }
      if (!typeRes3.type.equals("Number")) {
        error(argTypeMessage("third", function.getName(), "Number", typeRes3.type), function,
            SymboleoPackage.Literals.THREE_ARG_STRING_FUNCTION__ARG3);
      }
    }
    warnUnsupportedFunction(function);
  }

  /*
   * check type of internal functions
   */
  @Check(CheckType.FAST)
  public void checkStringFunctionArgsType3(ThreeArgDateFunction function) {
    if (function.getName().equals("Date.add")) {
      // resolve type of argument
      ResolveExpressionResult typeRes = Helpers.resolveExpressionType(function.getArg1(), this.variables,
          this.parameters);
      // show error if not a string
      if (typeRes.error != null) {
        error(typeRes.message, typeRes.error, typeRes.ref);
      }
      // L4: a bare Event variable is a valid date point -- its occurrence
      // timestamp (e.g. Date.add(assistanceProvided, 5, days) = five days
      // after the assistance happened). Accept it; the generator emits the
      // event's ._timestamp. Anything else must resolve to a Date.
      if (!typeRes.type.equals("Date") && !isEventPoint(function.getArg1())) {
        error("The first argument of '" + function.getName() + "' must be a "
            + "Date or an Event, but the given expression has type '" + typeRes.type
            + "'. Pass a date point: a Date-typed contract parameter, a date "
            + "attribute of an event (e.g. delivered.delDueDate), a bare Event "
            + "variable whose occurrence time is meant (e.g. assistanceProvided), "
            + "or another Date.add(...) expression.", function,
            SymboleoPackage.Literals.FUNCTION_CALL__ARG1);
      }

      // resolve second argument if an expression is used
      ResolveExpressionResult typeRes2 = Helpers.resolveExpressionType(function.getValue(), this.variables,
          this.parameters);
      if (typeRes2.error != null) {
        error(typeRes2.message, typeRes2.error, typeRes2.ref);
      }
      if (!typeRes2.type.equals("Number")) {
        error(argTypeMessage("second", function.getName(), "Number", typeRes2.type), function,
            SymboleoPackage.Literals.THREE_ARG_DATE_FUNCTION__VALUE);
      }

    }
  }

  /*
   * only variables of type Event shall be used inside VariableEvent
   */
  //AC-we added DataTransfer here as a special kind of event that use Env
  @Check(CheckType.FAST)
  public void checkVariableEventsType(VariableEvent event) {
    // get type of VariableDotExpression
    EObject typeRes = Helpers.getDotExpressionType(event.getVariable(), this.variables, this.parameters);
    if (!(typeRes instanceof RegularType)) {
      error(eventVariableMessage(event), event, SymboleoPackage.Literals.VARIABLE_EVENT__VARIABLE);
      return;
    }
    // get the parent type
    RegularType dt = (RegularType) typeRes;
    RegularType type = Helpers.getBaseType(dt);
    if (type == null) {
      error(eventVariableMessage(event), event, SymboleoPackage.Literals.VARIABLE_EVENT__VARIABLE);
    } else if (!(type.getOntologyType().getName().equalsIgnoreCase("event") || type.getOntologyType().getName().equalsIgnoreCase("datatransfer") )) {
      error(eventVariableMessage(event), event, SymboleoPackage.Literals.VARIABLE_EVENT__VARIABLE);
    }
  }

  private static String eventVariableMessage(VariableEvent event) {
    String name = baseVariableName(event.getVariable());
    String subject = name != null ? "'" + name + "'" : "The referenced element";
    return subject + " cannot be used as an event here: predicates such as "
        + "Happens/HappensBefore/HappensWithin accept only a variable whose "
        + "declared type is (transitively) 'isA Event' (or DataTransfer). "
        + "Reference an event variable instead, or change the variable's "
        + "type so it isA Event.";
  }

  private void warnUnsupportedFunction(FunctionCall function) {
    warning("Function '" + function.getName() + "' is not supported by the "
        + "nuXmv model checker and will be skipped in the generated .smv "
        + "model -- formal verification (SymboleoPC) will not see this "
        + "expression. Smart-contract code generation and execution are "
        + "unaffected; no change is needed unless you rely on model checking.",
        function, SymboleoPackage.Literals.FUNCTION_CALL__ARG1);
  }
  
  /*
   *  Symboleo ACPolicy Validation Rule
   ********************************************************************************/


  /*
   * check type of accessedRole and controller(by) in each Rule
   */
  @Check(CheckType.FAST)
  public void checkAccessedRoleAndControllerInRule(Model model) {
    // loop over rules
    for (Rule rule : model.getRules()) {
      // check accessedRole type
      EObject accessedRoleType = Helpers.getDotExpressionType(rule.getAccessedRole(), model.getVariables(), model.getParameters());
      // get the parameter type if it is a parameter
      if (accessedRoleType instanceof ParameterType && ((ParameterType) accessedRoleType).getDomainType() != null) {
    	  accessedRoleType = ((ParameterType) accessedRoleType).getDomainType();
      }
      if (accessedRoleType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) accessedRoleType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error("The role granted access in rule '" + rule.getName() + "' (the 'To ...' "
            + "part) must be a role instance: a variable or contract parameter "
            + "whose type is declared 'isA Role'. Reference a Role-typed "
            + "variable/parameter, or fix its type declaration.", rule,
              SymboleoPackage.Literals.RULE__ACCESSED_ROLE);
        }
      } else {
        error("The role granted access in rule '" + rule.getName() + "' (the 'To ...' "
            + "part) must be a role instance: a variable or contract parameter "
            + "whose type is declared 'isA Role'. Reference a Role-typed "
            + "variable/parameter, or fix its type declaration.", rule,
            SymboleoPackage.Literals.RULE__ACCESSED_ROLE);
      }

      // check controller type
      EObject controllerType = Helpers.getDotExpressionType(rule.getController(), model.getVariables(), model.getParameters());
      // get the parameter type if it is a parameter
      if (controllerType instanceof ParameterType && ((ParameterType) controllerType).getDomainType() != null) {
    	  controllerType = ((ParameterType) controllerType).getDomainType();
      }
      if (controllerType instanceof DomainType) {
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) controllerType);
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
          error("The granting role in rule '" + rule.getName() + "' (the 'By ...' part) "
            + "must be a role instance: a variable or contract parameter whose "
            + "type is declared 'isA Role'. Reference a Role-typed "
            + "variable/parameter, or fix its type declaration.", rule,
              SymboleoPackage.Literals.RULE__CONTROLLER);
        } else{///////////////////////////////////////////////////////////////////////****************************************************
        	/*
        	  if (rule.getAccessedResource() instanceof Resource) {
    		    List<Attribute> attributes = Helpers.getAttributesOfRegularType((RegularType) modelType);
    		    Resource resource = (Resource) rule.getAccessedResource();
      		    Ref lastRef = getLastRef(resource);

      		    if (lastRef instanceof VariableRef) {
      		        VariableRef variableRef = (VariableRef) lastRef;
      		        Variable variable = findVariable(variableRef.getVariable());
      		        List<Attribute> attributes = Helpers.getAttributesOfRegularType((RegularType) modelType);


      		        if (variable != null) {
      		            for (Assignment assignment : variable.getAttributes()) {
      		                if (assignment.getName().equals("owner") || assignment.name.equals("controller") || assignment.name.equals("performer")) {
      		                    if (assignment.value.equals(rule.controller)) {
      		                        // Valid rule
      		                      error("controller value in '" + rule.getName() + "' Valid'", rule,
      		                            SymboleoPackage.Literals.RULE__CONTROLLER);

      		                    }
      		                }
      		            }
      		            // None of the attributes match the controller role
      		          error("controller value in '" + rule.getName() + "' Error: No matching attribute found for the controller role'", rule,
		                          SymboleoPackage.Literals.RULE__CONTROLLER);
      		        } else {
      		        	error("controller value in '" + rule.getName() + "' Error: Variable not found'", rule,
		                          SymboleoPackage.Literals.RULE__CONTROLLER);
      		        }
      		    } else {
      		    	error("controller value in '" + rule.getName() + "' Error: Invalid accessed resource'", rule,
	                          SymboleoPackage.Literals.RULE__CONTROLLER);
      		    }
      		} else {
      			error("controller value in '" + rule.getName() + "' Error: Invalid accessed resource type'", rule,
                        SymboleoPackage.Literals.RULE__CONTROLLER);
      		}
      		*/
        	//////////////////////////////////////////////////////////////////////////*****************************************************
        }
      } else {
        error("The granting role in rule '" + rule.getName() + "' (the 'By ...' part) "
            + "must be a role instance: a variable or contract parameter whose "
            + "type is declared 'isA Role'. Reference a Role-typed "
            + "variable/parameter, or fix its type declaration.", rule,
            SymboleoPackage.Literals.RULE__CONTROLLER);
      }
    }// end for loop
  }// end function

  /*
   * check type of list of controller for ACPolicy
   */
  @Check(CheckType.FAST)
  public void checkControllerType(Model model) {
	  ACPolicy acpolicy = model.getAcpolicys();
    // The ACPolicy section is optional; a spec without it is valid (it just has
    // no access-control rules). Nothing to check, and dereferencing null here
    // would crash validation (SymboleoAC2SC#4, sibling of the codegen NPE).
    if (acpolicy == null) {
      return;
    }
    for (Controller controller : acpolicy.getController()) {
    	 Ref controllerType = controller.getControllerType();
    	 //System.out.println("before first if from dot expersstion" + controllerType);
      if (controllerType != null) {
        EObject resolvedType = Helpers.getDotExpressionType(controllerType, model.getVariables(), model.getParameters());
        //System.out.println("after first if from dot expersstion" + resolvedType);
        if (resolvedType instanceof ParameterType && ((ParameterType) resolvedType).getDomainType() != null) {
      	  //System.out.println("after first if from prameter type");
        	resolvedType = ((ParameterType) resolvedType).getDomainType();
      	  //System.out.println("after resolvetype in parameteer" + resolvedType);
        }
        if (resolvedType instanceof DomainType) {
        	//System.out.println("after domain type if" + resolvedType);
          RegularType baseType = Helpers.getBaseType((DomainType) resolvedType);
          //System.out.println("after RegularType type if" + baseType);
          if (baseType == null || baseType != null && !baseType.getOntologyType().getName().equals("Role")) {
            error("Each controller listed in the ACPolicy must be a role "
              + "instance: a variable or contract parameter whose type is "
              + "declared 'isA Role'. Reference a Role-typed "
              + "variable/parameter, or fix its type declaration.", controller,
            		SymboleoPackage.Literals.CONTROLLER__CONTROLLER_TYPE);
          }
        } else {
          error("Each controller listed in the ACPolicy must be a role "
              + "instance: a variable or contract parameter whose type is "
              + "declared 'isA Role'. Reference a Role-typed "
              + "variable/parameter, or fix its type declaration.", controller,
        		  SymboleoPackage.Literals.CONTROLLER__CONTROLLER_TYPE);
        }
      }
    }
  }

  /*
   * Identifiers should be unique
   */
  /*
  @Check(CheckType.FAST)
  public void checkIdentifiersAreUnique3(Model model) {

    Set<String> identifiers = new HashSet<>();

    for (Rule x : model.getRules()) {
      if (identifiers.contains(x.getName())) {
        error("Duplicate identifier " + x.getName(), x, SymboleoPackage.Literals.RULE__NAME);
      }
      identifiers.add(x.getName());
    }

  }*/

  //(1) check the resource type (after on) if it is variables or a attribute to get the attributes of the variables
  //(2) check the attributes that we get searching for the attributes with owner, controller, or performer.
  //(3) If the value of one of them equals after "by" role, then it is valid. otherwise error.

  /*
   *
   */
  /*
  @Check(CheckType.FAST)
  public void checkPermesstionGiverOfEachResource(Model model) {

  }*/





































  /*
   * check type of list of controller for ACPolicy
   */
  /*
  @Check(CheckType.FAST)
  public void checkControllerInACPolicy(Model model) {
    // loop over acpolicy
	ACPolicy acpolicy = model.getAcpolicys();
    for (Controller controller : acpolicy.getController() ) {
      // check role type ACPolicy controller
      EObject controllerType = Helpers.getDotExpressionType(controller.getControllerType(),model.getVariables(), model.getParameters());
      //System.out.println("after return from dot expersstion" + controller);
      // get the parameter type if it is a parameter
      if (controllerType instanceof ParameterType && ((ParameterType) controllerType).getDomainType() != null) {
    	  //System.out.println("after first if from dot expersstion");
    	  controllerType = ((ParameterType) controllerType).getDomainType();
    	  //System.out.println("after controllerType in first if from dot expersstion");
      }
      if (controllerType instanceof DomainType) {
    	  //System.out.println("after second if from dot expersstion");
        // error if it is not a Role
        RegularType base = Helpers.getBaseType((DomainType) controllerType);
        //System.out.println("after RegularType in seond if from dot expersstion" + base.getName()  );
        //if (base.getOntologyType().getName().equals("Role")) {
        //	System.out.println("it is a Role");
        //}
        if (base == null || base != null && !base.getOntologyType().getName().equals("Role")) {
        	//System.out.println("after third if from dot expersstion");
          error(" ACPolicy controller value in '" + controller.getName() + "' is not type of Role.'", controller,
              SymboleoPackage.Literals.CONTROLLER__CONTROLLER_TYPE);
        }
      } else {
    	  //System.out.println("inside else of seond if from dot expersstion");
        error(" ACPolicy controller value in '" + controller.getName()  + "' is not type of Role.'", controller,
            SymboleoPackage.Literals.CONTROLLER__CONTROLLER_TYPE);
      }

    }// end for loop
  }// end function
*/
  //error(" ACPolicy controller value in '" + name.substring(name.indexOf("variable:")+9, name.indexOf(")")) + "' is not type of Role.'", acpolicy, SymboleoPackage.Literals.AC_POLICY__CONTROLLER);
  //  error(" ACPolicy controller value in '" + acpolicy.getController().get(indexController) + "' is not type of Role.'", acpolicy,SymboleoPackage.Literals.AC_POLICY__CONTROLLER);



  /*
   * ==========================================================================
   * C7 validation rules (expert-reviewed tiering; see the SymboleoAC-Incoterms
   * repository, coverage/symboleoac-improvements.md, for the corpus evidence).
   * Errors:   E1 Event types need a Role-typed performer;
   *           E2 reserved / generated-name identifier collisions;
   *           E3 unique AC-rule names;
   *           E6 Role types need the AC attributes name/org/dept;
   *           E12a inheritance cycles (an error rather than a lint because a
   *                cycle previously crashed the compiler's own helpers).
   * (W8, arithmetic in an obligation consequent, was retired when the
   * LegalSituation metadata-builder defect it warned about -- SymboleoAC2SC#3
   * -- was fixed in Symboleo2SC.xtend.)
   * Warnings: W13 unused definitions -- domain types, contract parameters,
   *               and declared instances that nothing references.
   * Lints:    L9 permission giver should own/control/perform the resource;
   *           L11 dormant conditional norms;
   *           L12b cycles among variable initializations.
   *
   * Message convention (all tiers, including the pre-C7 checks above): every
   * diagnostic states (1) what is wrong, naming the offending element,
   * (2) why it matters downstream, and (3) how to fix it -- the messages are
   * consumed both by humans and by LLMs running compile-fix loops, so they
   * must be actionable without access to this source file.
   * ==========================================================================
   */

  // Identifiers that break the generated JavaScript/Java or collide with
  // members of the generated contract and domain classes.
  private static final Set<String> RESERVED_IDENTIFIERS = new HashSet<>(Arrays.asList(
      // JavaScript keywords and reserved words
      "break", "case", "catch", "class", "const", "continue", "debugger",
      "default", "delete", "do", "else", "enum", "export", "extends",
      "finally", "for", "function", "if", "import", "in", "instanceof",
      "new", "null", "return", "super", "switch", "this", "throw", "try",
      "typeof", "var", "void", "while", "with", "yield", "let", "static",
      "await", "implements", "interface", "package", "private", "protected",
      "public", "arguments", "eval",
      // Java keywords not already listed (the compiler pipeline is Java)
      "abstract", "assert", "boolean", "byte", "char", "double", "final",
      "float", "goto", "int", "long", "native", "short", "strictfp",
      "synchronized", "throws", "transient", "volatile",
      // members of the generated contract / domain classes and the js-core
      // runtime: a variable or attribute with one of these names silently
      // shadows generated state (e.g. a variable named `constructor`)
      "constructor", "prototype", "__proto__", "state", "activeState",
      "obligations", "powers", "survivingObligations", "notified",
      "accessPolicy", "authenticate", "activated", "terminated", "suspended",
      "resumed", "fulfilled", "violated", "expired", "discharged",
      "serialize", "deserialize", "events", "id",
      "_name", "_type", "_timestamp", "_controller", "_performer", "_events",
      "_value",
      // JavaScript globals and js-core exported class names (capitalized
      // domain-type names generate `class <Name>` declarations)
      "Object", "Function", "Array", "Boolean", "Number", "String", "Date",
      "Math", "JSON", "Promise", "Symbol", "Error", "Map", "Set", "Buffer",
      "Event", "Obligation", "Power", "Role", "Asset", "Party", "Contract",
      "SymboleoContract", "Predicates", "Events", "InternalEvent",
      "InternalEventSource", "InternalEventType", "LegalSituation", "Rule",
      "ACPolicy", "TimePoint", "TimeInterval", "Attribute", "Operation",
      "Resource", "DataTransfer", "StateTransition", "AbstractEvent"));

  private static String reservedMessage(String name, String what) {
    return what + " name '" + name + "' collides with a JavaScript/Java "
        + "reserved word or a member of the generated smart-contract classes; "
        + "the generated code would be invalid or silently corrupted. "
        + "Please rename it.";
  }

  // Walk a dot expression down to its base variable name, e.g. goods.description -> "goods".
  private static String baseVariableName(Ref ref) {
    Ref current = ref;
    while (current instanceof VariableDotExpression) {
      current = ((VariableDotExpression) current).getRef();
    }
    if (current instanceof VariableRef) {
      return ((VariableRef) current).getVariable();
    }
    return null;
  }

  /*
   * C7-E1: every Event type must declare (or inherit) a Role-typed
   * `performer` attribute. The generated event constructor and the
   * access-control layer both dereference it: an event without a performer
   * compiles and even parses as JavaScript, but is untriggerable on-chain.
   */
  @Check(CheckType.FAST)
  public void checkEventTypeHasRolePerformer(RegularType type) {
    RegularType base = Helpers.getBaseType(type);
    if (base == null || base.getOntologyType() == null) {
      return;
    }
    if (!base.getOntologyType().getName().equalsIgnoreCase("Event")) {
      return;
    }
    for (Attribute atr : Helpers.getAttributesOfRegularType(type)) {
      if (atr.getName().equals("performer")) {
        if (atr.getDomainType() != null) {
          RegularType atrBase = Helpers.getBaseType(atr.getDomainType());
          if (atrBase != null && atrBase.getOntologyType() != null
              && atrBase.getOntologyType().getName().equals("Role")) {
            return; // Role-typed performer present
          }
        }
        error("Event type '" + type.getName() + "' declares a 'performer' that "
            + "is not typed as a Role; the generated code and the "
            + "access-control layer require a Role-typed performer. Change "
            + "its type to a domain type declared 'isA Role' (e.g. "
            + "'performer: Seller' where 'Seller isA Role with name: String, "
            + "org: String, dept: String').", type,
            SymboleoPackage.Literals.DOMAIN_TYPE__NAME);
        return;
      }
    }
    error("Event type '" + type.getName() + "' must declare a Role-typed "
        + "'performer' attribute (e.g. 'performer: Seller'); without it the "
        + "generated event cannot be triggered on-chain.", type,
        SymboleoPackage.Literals.DOMAIN_TYPE__NAME);
  }

  /*
   * C7-E2: reserved / generated-name identifier collisions.
   */
  @Check(CheckType.FAST)
  public void checkDomainTypeNameReserved(DomainType type) {
    if (RESERVED_IDENTIFIERS.contains(type.getName())) {
      error(reservedMessage(type.getName(), "Domain type"), type,
          SymboleoPackage.Literals.DOMAIN_TYPE__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkVariableNameReserved(Variable v) {
    if (RESERVED_IDENTIFIERS.contains(v.getName())) {
      error(reservedMessage(v.getName(), "Variable"), v,
          SymboleoPackage.Literals.VARIABLE__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkParameterNameReserved(Parameter p) {
    if (RESERVED_IDENTIFIERS.contains(p.getName())) {
      error(reservedMessage(p.getName(), "Parameter"), p,
          SymboleoPackage.Literals.PARAMETER__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkAttributeNameReserved(Attribute a) {
    if (RESERVED_IDENTIFIERS.contains(a.getName())) {
      error(reservedMessage(a.getName(), "Attribute"), a,
          SymboleoPackage.Literals.ATTRIBUTE__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkObligationNameReserved(Obligation o) {
    if (RESERVED_IDENTIFIERS.contains(o.getName())) {
      error(reservedMessage(o.getName(), "Obligation"), o,
          SymboleoPackage.Literals.OBLIGATION__NAME);
    }
  }

  @Check(CheckType.FAST)
  public void checkPowerNameReserved(Power p) {
    if (RESERVED_IDENTIFIERS.contains(p.getName())) {
      error(reservedMessage(p.getName(), "Power"), p,
          SymboleoPackage.Literals.POWER__NAME);
    }
  }

  /*
   * C7-E3: AC-rule names must be unique (completes the check that was left
   * commented out).
   */
  @Check(CheckType.FAST)
  public void checkRuleNamesAreUnique(Model model) {
    Set<String> identifiers = new HashSet<>();
    for (Rule x : model.getRules()) {
      if (identifiers.contains(x.getName())) {
        error("Duplicate access-control rule name '" + x.getName() + "': every "
            + "rule in the ACPolicy section must have a unique name (the "
            + "generated policy indexes rules by name, so a duplicate would "
            + "silently shadow the earlier rule). Rename this rule.", x,
            SymboleoPackage.Literals.RULE__NAME);
      }
      identifiers.add(x.getName());
      if (RESERVED_IDENTIFIERS.contains(x.getName())) {
        error(reservedMessage(x.getName(), "Rule"), x,
            SymboleoPackage.Literals.RULE__NAME);
      }
    }
  }

  /*
   * C7-E6: every Role type must declare (or inherit) the attributes the
   * generated access-control `authenticate` matches against the caller's
   * certificate: name, org, dept. Without them, every transaction fails
   * on-chain with an opaque "Unauthorized" (SymboleoAC2SC issue #1).
   */
  @Check(CheckType.FAST)
  public void checkRoleTypeHasACAttributes(RegularType type) {
    RegularType base = Helpers.getBaseType(type);
    if (base == null || base.getOntologyType() == null) {
      return;
    }
    if (!base.getOntologyType().getName().equals("Role")) {
      return;
    }
    Set<String> names = new HashSet<>();
    for (Attribute atr : Helpers.getAttributesOfRegularType(type)) {
      names.add(atr.getName());
    }
    List<String> missing = new ArrayList<>();
    for (String required : Arrays.asList("name", "org", "dept")) {
      if (!names.contains(required)) {
        missing.add(required);
      }
    }
    if (!missing.isEmpty()) {
      error("Role type '" + type.getName() + "' is missing the access-control "
          + "attribute(s) " + missing + ": the generated authenticate() "
          + "matches the caller's certificate against name/org/dept, so a "
          + "role without them cannot be authorized on-chain (it fails with "
          + "an opaque \"Unauthorized\"). Declare all three, e.g. '"
          + type.getName() + " isA Role with name: String, org: String, "
          + "dept: String;'.", type,
          SymboleoPackage.Literals.DOMAIN_TYPE__NAME);
    }
  }

  /*
   * C7-E12a: inheritance cycles among domain types. An error rather than a
   * lint: a cycle used to send the compiler's own type-walking helpers into
   * unbounded recursion.
   */
  @Check(CheckType.FAST)
  public void checkInheritanceCycles(RegularType type) {
    Set<RegularType> visited = new HashSet<>();
    RegularType current = type;
    while (current != null) {
      if (!visited.add(current)) {
        error("Inheritance cycle: domain type '" + type.getName()
            + "' is (transitively) declared as a subtype of itself, so its "
            + "attributes cannot be resolved. Break the cycle by removing or "
            + "retargeting one of the 'isA' links in the chain (the topmost "
            + "type should extend an ontology type such as Role, Asset, or "
            + "Event).", type,
            SymboleoPackage.Literals.DOMAIN_TYPE__NAME);
        return;
      }
      current = current.getRegularType();
    }
  }

  /*
   * C7-W13: unused definitions. A domain type, contract parameter, or
   * declared instance that nothing references is either leftover from an
   * edit or a sign that an intended reference was never written. It also
   * has a real cost: every domain type generates a class, every parameter
   * must be supplied at instantiation, and every declared instance is
   * initialized in the deployed smart contract.
   *
   * Reference mechanics (they differ, deliberately handled separately):
   * - variables and parameters are referenced BY NAME through dot
   *   expressions (VariableRef holds a plain string), so usage is a scan
   *   for VariableRef leaves anywhere in the model;
   * - domain types are referenced through real EMF cross-references
   *   (a declaration's type, a parameter's type, an attribute's type, an
   *   isA supertype, an enumeration literal), so usage is a scan of
   *   eCrossReferences targets.
   * A definition referenced only by another unused definition counts as
   * used; fixing the first warning surfaces the next one (cascade).
   */
  @Check(CheckType.FAST)
  public void checkUnusedDefinitions(Model model) {
    Set<String> referencedNames = new HashSet<>();
    Set<DomainType> referencedTypes = new HashSet<>();
    TreeIterator<EObject> it = model.eAllContents();
    while (it.hasNext()) {
      EObject node = it.next();
      if (node instanceof VariableRef) {
        referencedNames.add(((VariableRef) node).getVariable());
      }
      for (EObject target : node.eCrossReferences()) {
        if (target instanceof DomainType) {
          referencedTypes.add((DomainType) target);
        }
      }
    }

    for (Parameter p : model.getParameters()) {
      if (!referencedNames.contains(p.getName())) {
        warning("Contract parameter '" + p.getName() + "' is never used: no "
            + "norm, declaration, constraint, or access-control rule references "
            + "it. Every parameter must be supplied when the contract is "
            + "instantiated, so an unused one burdens every deployment. Remove "
            + "'" + p.getName() + "' from the contract's parameter list (and "
            + "from instantiation call sites), or add the reference that was "
            + "intended.", p, SymboleoPackage.Literals.PARAMETER__NAME);
      }
    }

    for (Variable v : model.getVariables()) {
      if (!referencedNames.contains(v.getName())) {
        warning("Declared instance '" + v.getName() + "' is never used: no "
            + "obligation, power, precondition, postcondition, constraint, "
            + "access-control rule, or other declaration references it. It "
            + "would still be initialized in the deployed smart contract. "
            + "Remove the declaration from the Declarations section, or add "
            + "the reference that was intended.", v,
            SymboleoPackage.Literals.VARIABLE__NAME);
      }
    }

    for (DomainType t : model.getDomainTypes()) {
      if (!referencedTypes.contains(t)) {
        warning("Domain type '" + t.getName() + "' is never used: no "
            + "declaration, parameter, attribute, isA subtype, or enumeration "
            + "reference mentions it. Every domain type generates a class in "
            + "the smart contract. Remove the type from the Domain section, or "
            + "add the declaration/attribute that was meant to use it.", t,
            SymboleoPackage.Literals.DOMAIN_TYPE__NAME);
      }
    }
  }

  /*
   * C7-L9: the granting role in an access-control rule should be the owner,
   * controller, or performer of the granted resource (completes the check
   * that was left commented out). Informational.
   */
  @Check(CheckType.FAST)
  public void checkPermissionGiver(Model model) {
    for (Rule rule : model.getRules()) {
      Resource res = rule.getAccessedResource();
      if (!(res instanceof ResourceDot)) {
        continue; // norm/policy resources have no owner/controller/performer assignments
      }
      String resourceVarName = baseVariableName(((ResourceDot) res).getResourceDot());
      if (resourceVarName == null) {
        continue;
      }
      Optional<Variable> resourceVar = model.getVariables().stream()
          .filter(v -> v.getName().equals(resourceVarName)).findFirst();
      if (resourceVar.isEmpty()) {
        continue;
      }
      String controllerName = baseVariableName(rule.getController());
      if (controllerName == null) {
        continue;
      }
      boolean sawRelevantAssignment = false;
      boolean giverMatches = false;
      for (Assignment asg : resourceVar.get().getAttributes()) {
        AssignExpression ae = (AssignExpression) asg;
        if (!Arrays.asList("owner", "controller", "performer").contains(ae.getName())) {
          continue;
        }
        sawRelevantAssignment = true;
        // the assigned value is a variable reference like `:= seller`
        if (matchesVariable(ae.getValue(), controllerName)) {
          giverMatches = true;
          break;
        }
      }
      if (sawRelevantAssignment && !giverMatches) {
        info("Rule '" + rule.getName() + "': the granting role '" + controllerName
            + "' (after 'By') is not the owner, controller, or performer of "
            + "resource '" + resourceVarName + "', so it has no evident "
            + "authority to grant access to it. If this is unintended, grant "
            + "'By' the resource's owner/controller/performer instead, or make '"
            + controllerName + "' one of them in the declaration of '"
            + resourceVarName + "'. If the grant is deliberate (e.g. delegated "
            + "authority), this note can be ignored.", rule,
            SymboleoPackage.Literals.RULE__CONTROLLER);
      }
    }
  }

  private static boolean matchesVariable(EObject expression, String variableName) {
    if (expression == null) {
      return false;
    }
    if (expression instanceof VariableRef) {
      return variableName.equals(((VariableRef) expression).getVariable());
    }
    TreeIterator<EObject> it = expression.eAllContents();
    while (it.hasNext()) {
      EObject n = it.next();
      if (n instanceof VariableRef
          && variableName.equals(((VariableRef) n).getVariable())) {
        return true;
      }
    }
    return false;
  }

  /*
   * C7-L11: dormant conditional norms. A norm whose trigger waits on an event
   * that (a) no other norm interacts with and (b) has no performer path (its
   * type carries no performer attribute, so no party can bring it about) can
   * never awaken. Informational.
   */
  @Check(CheckType.FAST)
  public void checkDormantNorms(Model model) {
    List<EObject> norms = new ArrayList<>();
    norms.addAll(model.getObligations());
    norms.addAll(model.getSurvivingObligations());
    norms.addAll(model.getPowers());

    for (EObject norm : norms) {
      Proposition trigger = (norm instanceof Obligation)
          ? ((Obligation) norm).getTrigger()
          : ((Power) norm).getTrigger();
      if (trigger == null) {
        continue;
      }
      for (String eventVar : collectEventVariableNames(trigger)) {
        // (b) performer path: the event's type declares a performer
        Optional<Variable> varDecl = model.getVariables().stream()
            .filter(v -> v.getName().equals(eventVar)).findFirst();
        boolean hasPerformer = false;
        if (varDecl.isPresent() && varDecl.get().getType() != null) {
          for (Attribute atr : Helpers.getAttributesOfRegularType(varDecl.get().getType())) {
            if (atr.getName().equals("performer")) {
              hasPerformer = true;
              break;
            }
          }
        }
        if (hasPerformer) {
          continue;
        }
        // (a) referenced by any other norm?
        boolean referencedElsewhere = false;
        for (EObject other : norms) {
          if (other == norm) {
            continue;
          }
          if (normReferencesEvent(other, eventVar)) {
            referencedElsewhere = true;
            break;
          }
        }
        if (!referencedElsewhere) {
          if (norm instanceof Obligation) {
            info(dormantMessage(((Obligation) norm).getName(), eventVar), norm,
                SymboleoPackage.Literals.OBLIGATION__NAME);
          } else {
            info(dormantMessage(((Power) norm).getName(), eventVar), norm,
                SymboleoPackage.Literals.POWER__NAME);
          }
        }
      }
    }
  }

  private static String dormantMessage(String normName, String eventVar) {
    return "Norm '" + normName + "' may be dormant: its trigger waits on "
        + "event '" + eventVar + "', which no other norm interacts with and "
        + "whose type declares no performer, so no party is modelled as able "
        + "to bring it about. If the norm should be reachable, give the "
        + "event's type a Role-typed performer or reference the event from "
        + "the norm that produces it; if the event is supplied purely by the "
        + "environment, this note can be ignored.";
  }

  private static Set<String> collectEventVariableNames(EObject proposition) {
    Set<String> names = new HashSet<>();
    if (proposition instanceof VariableEvent) {
      String n = baseVariableName(((VariableEvent) proposition).getVariable());
      if (n != null) {
        names.add(n);
      }
    }
    TreeIterator<EObject> it = proposition.eAllContents();
    while (it.hasNext()) {
      EObject node = it.next();
      if (node instanceof VariableEvent) {
        String n = baseVariableName(((VariableEvent) node).getVariable());
        if (n != null) {
          names.add(n);
        }
      }
    }
    return names;
  }

  private static boolean normReferencesEvent(EObject norm, String eventVar) {
    List<Proposition> parts = new ArrayList<>();
    if (norm instanceof Obligation) {
      Obligation o = (Obligation) norm;
      parts.add(o.getTrigger());
      parts.add(o.getAntecedent());
      parts.add(o.getConsequent());
    } else if (norm instanceof Power) {
      Power p = (Power) norm;
      parts.add(p.getTrigger());
      parts.add(p.getAntecedent());
    }
    for (Proposition part : parts) {
      if (part != null && collectEventVariableNames(part).contains(eventVar)) {
        return true;
      }
    }
    return false;
  }

  /*
   * C7-L12b: cycles among variable initializations (a := b.x, b := a.y).
   * Informational.
   */
  @Check(CheckType.FAST)
  public void checkVariableInitializationCycles(Model model) {
    Set<String> variableNames = new HashSet<>();
    for (Variable v : model.getVariables()) {
      variableNames.add(v.getName());
    }
    Map<String, Set<String>> edges = new HashMap<>();
    for (Variable v : model.getVariables()) {
      Set<String> refs = new HashSet<>();
      for (Assignment asg : v.getAttributes()) {
        EObject value = ((AssignExpression) asg).getValue();
        if (value == null) {
          continue;
        }
        if (value instanceof VariableRef) {
          String n = ((VariableRef) value).getVariable();
          if (variableNames.contains(n)) {
            refs.add(n);
          }
        }
        TreeIterator<EObject> it = value.eAllContents();
        while (it.hasNext()) {
          EObject node = it.next();
          if (node instanceof VariableRef) {
            String n = ((VariableRef) node).getVariable();
            if (variableNames.contains(n)) {
              refs.add(n);
            }
          }
        }
      }
      edges.put(v.getName(), refs);
    }
    Set<String> reported = new HashSet<>();
    for (Variable v : model.getVariables()) {
      if (reported.contains(v.getName())) {
        continue;
      }
      if (hasPathBackTo(v.getName(), v.getName(), edges, new HashSet<>())) {
        reported.add(v.getName());
        info("Variable '" + v.getName() + "' participates in an initialization "
            + "cycle: its declaration (transitively) references itself through "
            + "the ':=' assignments, so the instances cannot be constructed in "
            + "a well-defined order. Break the cycle by initializing one of "
            + "the variables involved from a literal or a contract parameter "
            + "instead of from another declaration.", v,
            SymboleoPackage.Literals.VARIABLE__NAME);
      }
    }
  }

  private static boolean hasPathBackTo(String target, String current,
      Map<String, Set<String>> edges, Set<String> visited) {
    Set<String> next = edges.getOrDefault(current, java.util.Collections.emptySet());
    for (String n : next) {
      if (n.equals(target)) {
        return true;
      }
      if (visited.add(n) && hasPathBackTo(target, n, edges, visited)) {
        return true;
      }
    }
    return false;
  }

}// end of the class

// warning about common keywords of Java, js , etc
// Role, Asset, Event, when, for foreach while if else function __prototype 
// args functions should resolve correctly
// env vars should not be used in variables
// model inheritance should not have cycles
// variables used in expressions should not have cycles



