import type { ContractModel } from './api.js';
import { saveBlobAs } from '../fileio.js';

// nowrap keeps each cell on one line so the table takes its natural width and
// the container's overflow:auto provides a horizontal scrollbar (instead of the
// text wrapping and squeezing the table to fit).
const cell: React.CSSProperties = { border: '1px solid #3a3d41', padding: '4px 8px', fontSize: 12, verticalAlign: 'top', whiteSpace: 'nowrap' };
const head: React.CSSProperties = { ...cell, background: '#2d2d30', color: '#9cdcfe', position: 'sticky', top: 0 };
const saveBtn: React.CSSProperties = {
  padding: '2px 10px', background: '#3a3d41', color: '#fff', border: '1px solid #555',
  borderRadius: 3, cursor: 'pointer', font: '12px ui-monospace, monospace',
};

// HTML-escape a value for safe inclusion in the exported document.
const esc = (s: string) =>
  (s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export function Matrix({ model }: { model: ContractModel | null }) {
  if (!model) return <Msg>Matrix appears after the model loads.</Msg>;
  const rules = model.rules ?? [];
  if (rules.length === 0) return <Msg>No <code>ACPolicy</code> rules in this contract.</Msg>;

  // Rows = accessed roles, columns = accessed resources.
  const roles = [...new Set(rules.map((r) => r.role).filter(Boolean))];
  const resources = [...new Set(rules.map((r) => r.resource).filter(Boolean))];

  const at = (role: string, resource: string) =>
    rules.filter((r) => r.role === role && r.resource === resource);

  // Export the matrix as a single self-contained, styled HTML document.
  const saveHtml = () => {
    const title = `${model.contractName || 'Contract'} — Access-Control Policy`;
    const headCells = resources.map((res) => `<th>${esc(res)}</th>`).join('');
    const bodyRows = roles.map((role) => {
      const cells = resources.map((res) => {
        const items = at(role, res).map((r) => {
          const grant = r.action === 'Grant';
          return `<div class="${grant ? 'grant' : 'revoke'}" title="rule ${esc(r.name)}, by ${esc(r.controller)}">`
            + `${grant ? '✓' : '✗'} ${esc(r.permission)}</div>`;
        }).join('');
        return `<td>${items}</td>`;
      }).join('');
      return `<tr><th class="role">${esc(role)}</th>${cells}</tr>`;
    }).join('\n');
    const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
  :root { color-scheme: light; }
  body { font: 14px/1.5 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #1e1e1e; margin: 2rem; }
  h1 { font-size: 1.3rem; margin: 0 0 .25rem; }
  .meta { color: #555; margin: 0 0 1rem; }
  table { border-collapse: collapse; }
  th, td { border: 1px solid #c8c8c8; padding: 6px 10px; vertical-align: top; text-align: left; }
  thead th { background: #f0f3f7; }
  th.corner { background: #e8ecf1; }
  th.role { background: #f7f9fb; font-weight: 600; white-space: nowrap; }
  td div { white-space: nowrap; }
  .grant { color: #1a7f37; }
  .revoke { color: #b42318; }
  footer { color: #888; font-size: 12px; margin-top: 1.25rem; }
</style>
</head>
<body>
<h1>${esc(title)}</h1>
<p class="meta">Access-control matrix — roles (rows) × resources (columns).${
      model.acControllers.length > 0 ? ` Policy controller: <b>${esc(model.acControllers.join(', '))}</b>.` : ''
    }</p>
<table>
<thead><tr><th class="corner">role \\ resource</th>${headCells}</tr></thead>
<tbody>
${bodyRows}
</tbody>
</table>
<footer>Generated by the SymboleoAC Web IDE.</footer>
</body>
</html>
`;
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    void saveBlobAs(`${model.contractName || 'contract'}-policy.html`, blob, { 'text/html': ['.html'] });
  };

  // Same structure as the diagram views (MermaidView): a flex-column root with a
  // fixed header and a dedicated flex:1 scroller. The scroller — not a plain
  // height:100% block — is what reliably gives the wide table a horizontal
  // scrollbar inside the resizable panel.
  return (
    <div style={{ height: '100%', width: '100%', display: 'flex', flexDirection: 'column' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 10px 6px' }}>
        <div style={{ color: '#9cdcfe', fontSize: 11 }}>
          Access-control matrix — roles (rows) × resources (columns).
          {model.acControllers.length > 0 && <> Policy controller: <b>{model.acControllers.join(', ')}</b>.</>}
        </div>
        <button type="button" style={{ ...saveBtn, marginLeft: 'auto' }} title="Save matrix as a formatted HTML file" onClick={saveHtml}>Save</button>
      </div>
      <div style={{ flex: 1, minHeight: 0, minWidth: 0, width: '100%', boxSizing: 'border-box', overflow: 'auto', padding: '0 10px 10px' }}>
        <table style={{ borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th style={head}>role \ resource</th>
              {resources.map((res) => <th key={res} style={head}>{res}</th>)}
            </tr>
          </thead>
          <tbody>
            {roles.map((role) => (
              <tr key={role}>
                <td style={{ ...cell, color: '#d4d4d4', fontWeight: 600 }}>{role}</td>
                {resources.map((res) => (
                  <td key={res} style={cell}>
                    {at(role, res).map((r, i) => (
                      <div key={i} title={`rule ${r.name}, by ${r.controller}`}>
                        <span style={{ color: r.action === 'Grant' ? '#a6e22e' : '#f48771' }}>
                          {r.action === 'Grant' ? '✓' : '✗'} {r.permission}
                        </span>
                      </div>
                    ))}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function Msg({ children }: { children: React.ReactNode }) {
  return <div style={{ padding: 12, color: '#9cdcfe' }}>{children}</div>;
}
