/*
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.ui.tests;

import ca.uottawa.csmlab.symboleo.ui.internal.SymboleoActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SymboleoUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SymboleoActivator.getInstance().getInjector("ca.uottawa.csmlab.symboleo.Symboleo");
	}

}
