/*
 * generated by Xtext 2.36.0
 */
package ca.uottawa.csmlab.symboleo.ui;

import ca.uottawa.csmlab.symboleo.ui.internal.SymboleoActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SymboleoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SymboleoActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SymboleoActivator activator = SymboleoActivator.getInstance();
		return activator != null ? activator.getInjector(SymboleoActivator.CA_UOTTAWA_CSMLAB_SYMBOLEO_SYMBOLEO) : null;
	}

}
